package com.digital_enabling.android_aries_sdk.common

enum class ErrorCode {
    WALLET_ALREADY_PROVISIONED,
    RECORD_NOT_FOUND,
    RECORD_IN_INVALID_STATE,
    LEDGER_OPERATION_REJECTED,
    ROUTE_MESSAGE_ERROR,
    A2A_MESSAGE_TRANSMISSION_ERROR,
    INVALID_MESSAGE,
    MESSAGE_UNPACK_ERROR,
    INVALID_PARAMETER_FORMAT,
    INVALID_RECORD_DATA,
    PAYMENT_INSUFFICIENT_FUNDS,
    INVALID_PROOF_ENCODING,
    EVOCATION_REGISTRY_UNAVAILABLE,
    REVOCATION_INTERVAL_OUT_OF_RANGE,
    LEDGER_ITEM_NOT_FOUND
}